[package]
name = "newnes"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
log = "0.4.20"
env_logger = "0.10.1"
minifb = "0.25.0"

[profile.release]
lto = true
codegen-units = 1
